In [1]:
from utils_phoneme_reco import *

/home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/speechbrain/utils/torch_audio_backend.py:57: UserWarning: torchaudio._backend.list_audio_backends has been deprecated. This deprecation is part of a large refactoring effort to transition TorchAudio into a maintenance phase. The decoding and encoding capabilities of PyTorch for both audio and video are being consolidated into TorchCodec. Please see https://github.com/pytorch/audio/issues/3902 for more information. It will be removed from the 2.9 release.
  available_backends = torchaudio.list_audio_backends()

# Wav2vec+CTC

In [9]:

MODEL_ID = "/vol/experiments3/imbenamor/TAPAS-FRAIS/models/wav2vec2-french-phonemizer"

model = AutoModelForCTC.from_pretrained(MODEL_ID)
processor = Wav2Vec2Processor.from_pretrained(MODEL_ID)

device = "cuda"
model = model.to(device)
model.eval()

Wav2Vec2ForCTC(
  (wav2vec2): Wav2Vec2Model(
    (feature_extractor): Wav2Vec2FeatureEncoder(
      (conv_layers): ModuleList(
        (0): Wav2Vec2GroupNormConvLayer(
          (conv): Conv1d(1, 512, kernel_size=(10,), stride=(5,), bias=False)
          (activation): GELUActivation()
          (layer_norm): GroupNorm(512, 512, eps=1e-05, affine=True)
        )
        (1-4): 4 x Wav2Vec2NoLayerNormConvLayer(
          (conv): Conv1d(512, 512, kernel_size=(3,), stride=(2,), bias=False)
          (activation): GELUActivation()
        )
        (5-6): 2 x Wav2Vec2NoLayerNormConvLayer(
          (conv): Conv1d(512, 512, kernel_size=(2,), stride=(2,), bias=False)
          (activation): GELUActivation()
        )
      )
    )
    (feature_projection): Wav2Vec2FeatureProjection(
      (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (projection): Linear(in_features=512, out_features=768, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): Wav2Vec2Encoder(
      (pos_conv_embed): Wav2Vec2PositionalConvEmbedding(
        (conv): ParametrizedConv1d(
          768, 768, kernel_size=(128,), stride=(1,), padding=(64,), groups=16
          (parametrizations): ModuleDict(
            (weight): ParametrizationList(
              (0): _WeightNorm()
            )
          )
        )
        (padding): Wav2Vec2SamePadLayer()
        (activation): GELUActivation()
      )
      (layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (layers): ModuleList(
        (0-11): 12 x Wav2Vec2EncoderLayer(
          (attention): Wav2Vec2Attention(
            (k_proj): Linear(in_features=768, out_features=768, bias=True)
            (v_proj): Linear(in_features=768, out_features=768, bias=True)
            (q_proj): Linear(in_features=768, out_features=768, bias=True)
            (out_proj): Linear(in_features=768, out_features=768, bias=True)
          )
          (dropout): Dropout(p=0.1, inplace=False)
          (layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (feed_forward): Wav2Vec2FeedForward(
            (intermediate_dropout): Dropout(p=0.0, inplace=False)
            (intermediate_dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
            (output_dense): Linear(in_features=3072, out_features=768, bias=True)
            (output_dropout): Dropout(p=0.1, inplace=False)
          )
          (final_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        )
      )
    )
  )
  (dropout): Dropout(p=0, inplace=False)
  (lm_head): Linear(in_features=768, out_features=61, bias=True)
)

In [8]:
!wc -l /vol/corpora/Rhapsodie/TextGrid.phones.sampa

0 /vol/corpora/Rhapsodie/TextGrid.phones.sampa
wc: /vol/corpora/Rhapsodie/TextGrid.phones.sampa: Is a directory

# WavLM+CTC

In [2]:
import torch, librosa
from transformers import WavLMForCTC, Wav2Vec2FeatureExtractor, Wav2Vec2PhonemeCTCTokenizer

#CKPT = "/vol/experiments3/imbenamor/TAPAS-FRAIS/src/finetuning/wavlm-fr-phoneme/checkpoint-268600"
CKPT = "/vol/experiments3/imbenamor/TAPAS-FRAIS/src/finetuning/wavlm-fr-phoneme-large/checkpoint-476220"
ROOT = "/vol/experiments3/imbenamor/TAPAS-FRAIS/src/finetuning/wavlm-fr-phoneme-large"          # where vocab.json / tokenizer were saved

device = "cuda"
model = WavLMForCTC.from_pretrained(CKPT).to(device).eval()
feat  = Wav2Vec2FeatureExtractor.from_pretrained(CKPT)   # also present in CKPT
tok   = Wav2Vec2PhonemeCTCTokenizer.from_pretrained(ROOT)
tok.unk_token = "[UNK]"
tok.pad_token = "[PAD]"
model = model.to(device)
model.eval()

WavLMForCTC(
  (wavlm): WavLMModel(
    (feature_extractor): WavLMFeatureEncoder(
      (conv_layers): ModuleList(
        (0): WavLMLayerNormConvLayer(
          (conv): Conv1d(1, 512, kernel_size=(10,), stride=(5,), bias=False)
          (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
          (activation): GELUActivation()
        )
        (1-4): 4 x WavLMLayerNormConvLayer(
          (conv): Conv1d(512, 512, kernel_size=(3,), stride=(2,), bias=False)
          (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
          (activation): GELUActivation()
        )
        (5-6): 2 x WavLMLayerNormConvLayer(
          (conv): Conv1d(512, 512, kernel_size=(2,), stride=(2,), bias=False)
          (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
          (activation): GELUActivation()
        )
      )
    )
    (feature_projection): WavLMFeatureProjection(
      (layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (projection): Linear(in_features=512, out_features=1024, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): WavLMEncoderStableLayerNorm(
      (pos_conv_embed): WavLMPositionalConvEmbedding(
        (conv): ParametrizedConv1d(
          1024, 1024, kernel_size=(128,), stride=(1,), padding=(64,), groups=16
          (parametrizations): ModuleDict(
            (weight): ParametrizationList(
              (0): _WeightNorm()
            )
          )
        )
        (padding): WavLMSamePadLayer()
        (activation): GELUActivation()
      )
      (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (layers): ModuleList(
        (0): WavLMEncoderLayerStableLayerNorm(
          (attention): WavLMAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (gru_rel_pos_linear): Linear(in_features=64, out_features=8, bias=True)
            (rel_attn_embed): Embedding(320, 16)
          )
          (dropout): Dropout(p=0.1, inplace=False)
          (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (feed_forward): WavLMFeedForward(
            (intermediate_dropout): Dropout(p=0.0, inplace=False)
            (intermediate_dense): Linear(in_features=1024, out_features=4096, bias=True)
            (intermediate_act_fn): GELUActivation()
            (output_dense): Linear(in_features=4096, out_features=1024, bias=True)
            (output_dropout): Dropout(p=0.1, inplace=False)
          )
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
        (1-23): 23 x WavLMEncoderLayerStableLayerNorm(
          (attention): WavLMAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (gru_rel_pos_linear): Linear(in_features=64, out_features=8, bias=True)
          )
          (dropout): Dropout(p=0.1, inplace=False)
          (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (feed_forward): WavLMFeedForward(
            (intermediate_dropout): Dropout(p=0.0, inplace=False)
            (intermediate_dense): Linear(in_features=1024, out_features=4096, bias=True)
            (intermediate_act_fn): GELUActivation()
            (output_dense): Linear(in_features=4096, out_features=1024, bias=True)
            (output_dropout): Dropout(p=0.1, inplace=False)
          )
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
    )
  )
  (dropout): Dropout(p=0.0, inplace=False)
  (lm_head): Linear(in_features=1024, out_features=39, bias=True)
)

# Whisper+CTC

In [2]:
#whisper
from transformers import WhisperFeatureExtractor, Wav2Vec2PhonemeCTCTokenizer

CKPT = "/vol/experiments3/imbenamor/TAPAS-FRAIS/whisper-fr-phoneme/checkpoint-193924"
ROOT = "/vol/experiments3/imbenamor/TAPAS-FRAIS/whisper-fr-phoneme"
device = "cuda"
model = WhisperEncoderForCTC.from_pretrained(CKPT).to(device).eval()
feat  = WhisperFeatureExtractor.from_pretrained(CKPT)
tok   = Wav2Vec2PhonemeCTCTokenizer.from_pretrained(ROOT)
tok.unk_token = "[UNK]"
tok.pad_token = "[PAD]"

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'WhisperTokenizer'.
The class this function is called from is 'Wav2Vec2PhonemeCTCTokenizer'.

In [3]:
import os
import json
from pathlib import Path
import pandas as pd
import pickle

style = pd.read_csv("/vol/corpora/Rhapsodie/wav_style.csv")
audio_dir = "/vol/corpora/Rhapsodie/wav16k_corrected_withsilence"
textgrid_dir = Path("/vol/corpora/Rhapsodie/TextGrid.phones.sampa")
model_name = "whisper"

ref_inventory = set()
hyp_inventory = set()
alignment_store = {}

for filepath in textgrid_dir.glob("*"):
    print(filepath)
    f = filepath.stem[:-4] + ".wav"
    audio_path = os.path.join(audio_dir, f)

    if os.path.exists(audio_path) and f !="Rhap-D2004.wav":
        s = list(
            style[style["file"] == f.split("-")[1].split(".")[0]]["style"]
        )[0]

        textgrid_path = os.path.join(
            textgrid_dir,
            f.replace(".wav", "-Pro.TextGrid")
        )
        if model_name =="whisper":
            pred_phonemes, pred_alignments = get_phoneme_alignments_whisper_ctcfa(model, feat,tok, audio_path)
        elif model_name == "wavlm":
            pred_phonemes, pred_alignments = get_phoneme_alignments_wavlm_ctcfa(model, feat,tok, audio_path)
        else:
            pred_phonemes, pred_alignments = get_phoneme_alignments_w2v_ctcfa(model, processor, audio_path)

        ref_alignments = get_reference_alignments(
            textgrid_path,
            t="sampa"
        )

        clean_hyp = clean_alignment_dict(pred_alignments, is_hyp=True)
        clean_ref = clean_alignment_dict(
            ref_alignments,
            flag="",
            is_hyp=False
        )

        ref_seq = extract_phoneme_sequence(clean_ref)
        hyp_seq = extract_phoneme_sequence(clean_hyp)
        # collect inventories
        for ph in ref_seq:
            ref_inventory.add(ph)

        for ph in hyp_seq:
            hyp_inventory.add(ph)

        entry = {
            "file": f,
            "style": s,
            "ref_intervals": clean_ref,#get_ref_intervals_rhap(clean_ref, audio_path),
            "hyp_intervals": clean_hyp, #get_hyp_intervals(clean_hyp),
            "ref_seq": ref_seq,
            "hyp_seq": hyp_seq,
        }

        alignment_store[f] = entry

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D0020-Pro.TextGrid

/home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/pyannote/audio/utils/reproducibility.py:74: ReproducibilityWarning: TensorFloat-32 (TF32) has been disabled as it might lead to reproducibility issues and lower accuracy.
It can be re-enabled by calling
   >>> import torch
   >>> torch.backends.cuda.matmul.allow_tf32 = True
   >>> torch.backends.cudnn.allow_tf32 = True
See https://github.com/pyannote/pyannote-audio/issues/1370 for more details.

  warnings.warn(
/vol/experiments3/imbenamor/TAPAS-FRAIS/src/utils/utils_phoneme_reco.py:120: UserWarning: torchaudio.functional._alignment.forced_align has been deprecated. This deprecation is part of a large refactoring effort to transition TorchAudio into a maintenance phase. Please see https://github.com/pytorch/audio/issues/3902 for more information. It will be removed from the 2.9 release.
  aligned, _ = torchaudio.functional.forced_align(
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D2002-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0009-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D0017-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D2006-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0002-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D2009-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0023-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D0001-Pro.TextGrid
/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D0005-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0016-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0003-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D0004-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D2005-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D0002-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0006-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D1002-Pro.TextGrid
/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D1001-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0004-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D2012-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D2010-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0019-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M2005-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M1001-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0007-Pro.TextGrid
/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M2004-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D2011-Pro.TextGrid
/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D1003-Pro.TextGrid
/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D0003-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D2008-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0018-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D0006-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0022-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D2004-Pro.TextGrid
/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0001-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M2001-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D2007-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0011-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M1003-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0024-Pro.TextGrid
/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D2001-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D2013-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M2002-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D0008-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M2003-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0005-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D0009-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0021-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D2003-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0014-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0015-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M2006-Pro.TextGrid
/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-D0007-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0013-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0012-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0008-Pro.TextGrid

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.5. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../../../home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`

/vol/corpora/Rhapsodie/TextGrid.phones.sampa/Rhap-M0010-Pro.TextGrid

In [4]:
# ==========================
# Inventory comparison
# ==========================

print(f"Reference inventory size: {len(ref_inventory)}")
print(f"Hypothesis inventory size: {len(hyp_inventory)}")

only_in_ref = sorted(ref_inventory - hyp_inventory)
only_in_hyp = sorted(hyp_inventory - ref_inventory)

if not only_in_ref and not only_in_hyp:
    print("\n✓ REF and HYP inventories are identical.")
else:
    print("\n✗ Inventories differ.")

    if only_in_ref:
        print("\nPhonemes present only in REF:")
        print(only_in_ref)

    if only_in_hyp:
        print("\nPhonemes present only in HYP:")
        print(only_in_hyp)

# Optional: print full inventories
print("\nREF inventory:")
print(sorted(ref_inventory))

print("\nHYP inventory:")
print(sorted(hyp_inventory))

Reference inventory size: 34
Hypothesis inventory size: 34

✗ Inventories differ.

Phonemes present only in REF:
['ɥ']

Phonemes present only in HYP:
['ŋ']

REF inventory:
['a', 'b', 'd', 'e', 'f', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 's', 't', 'u', 'v', 'w', 'y', 'z', 'ø', 'œ', 'ɑ̃', 'ɔ', 'ɔ̃', 'ə', 'ɛ', 'ɛ̃', 'ɡ', 'ɥ', 'ɲ', 'ʁ', 'ʃ', 'ʒ']

HYP inventory:
['a', 'b', 'd', 'e', 'f', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 's', 't', 'u', 'v', 'w', 'y', 'z', 'ø', 'ŋ', 'œ', 'ɑ̃', 'ɔ', 'ɔ̃', 'ə', 'ɛ', 'ɛ̃', 'ɡ', 'ɲ', 'ʁ', 'ʃ', 'ʒ']

In [5]:
from metrics import *
import pickle
from jiwer import process_words
# (optional) save back so you don't redo it
with open(f"ctc_results/alignment_{model_name}_rhap.pkl", "wb") as f:
    pickle.dump(alignment_store, f)

In [6]:
from metrics_alignment import *

with open(f"ctc_results/alignment_{model_name}_rhap.pkl", "rb") as f:
    alignment_store = pickle.load(f)
compute_metrics(alignment_store, f"ctc_results/metrics++_{model_name}_rhap.csv", per_phoneme_csv=None)

,group,style,K,AAS (ms),Median_start (ms),Mean_start (ms),Median_end (ms),Mean_end (ms),P90 (ms),%>50ms,...,Median_dur (ms),%dur>50ms,N_ref,N_hyp,PER (%),Deletions,Insertions,F1@0ms (%),F1@20ms (%),F1@50ms (%)
0,Rhap-D0020.wav,spont,251,62.347978,40.8625,42.150568,42.9175,82.545388,79.8625,36.454183,...,20.000,16.334661,297,275,17.171717,27,5,0.0,48.601399,82.867133
1,Rhap-D2002.wav,planned,1863,49.904442,33.0625,40.568179,35.3125,59.240705,77.7325,26.355341,...,20.000,16.800859,2519,2228,28.066693,342,51,0.0,41.668422,78.491679
2,Rhap-M0009.wav,spont,471,57.859952,44.8075,47.265812,47.6875,68.454092,86.8125,43.949045,...,23.300,18.683652,555,519,16.036036,41,5,0.0,36.871508,76.350093
3,Rhap-D0017.wav,spont,288,60.440252,47.4000,49.283576,48.7000,71.596927,87.7500,47.916667,...,25.950,18.750000,319,310,11.598746,15,6,0.0,40.381558,71.542130
4,Rhap-D2006.wav,planned,810,58.135225,35.8400,38.616438,38.3875,77.654012,85.0625,30.802469,...,30.000,23.456790,943,888,15.164369,65,10,0.0,44.565811,78.427089
5,Rhap-M0002.wav,spont,413,50.499831,31.6625,36.776071,34.7375,64.223590,84.7375,26.634383,...,22.100,21.307506,529,471,22.495274,61,3,0.0,42.200000,80.000000
6,Rhap-D2009.wav,planned,2759,48.710219,37.8125,42.995617,38.8875,54.424821,78.0125,32.149329,...,20.000,17.796303,3062,2967,11.724363,151,56,0.0,33.239343,78.387792
7,Rhap-M0023.wav,spont,549,62.347108,28.6875,36.897172,32.0375,87.797045,82.6125,22.768670,...,20.000,19.489982,735,652,27.755102,101,18,0.0,44.844989,82.624369
8,Rhap-D0005.wav,spont,1705,54.415340,27.6875,40.404295,29.0625,68.426386,70.2975,20.586510,...,20.000,17.712610,2412,2029,31.094527,426,43,0.0,44.764693,78.766044
9,Rhap-M0016.wav,spont,514,68.587865,48.1625,53.763278,50.0250,83.412451,100.2375,48.540856,...,30.000,26.070039,633,585,21.011058,62,14,0.0,37.931034,73.070608
10,Rhap-M0003.wav,spont,798,51.543214,39.8375,42.165288,42.0375,60.921140,73.3375,32.017544,...,19.800,11.654135,937,870,16.008538,78,11,0.0,38.406198,78.140564
11,Rhap-D0004.wav,semi,2472,44.023307,31.0625,37.285730,33.1875,50.760884,68.9000,22.188511,...,20.000,15.655340,2995,2751,18.964942,289,45,0.0,41.280891,81.065089
12,Rhap-D2005.wav,planned,2681,43.411612,30.9375,36.022410,31.5625,50.800814,67.8125,22.006714,...,20.000,15.479299,3069,2940,14.532421,187,58,0.0,43.734398,84.207023
13,Rhap-D0002.wav,semi,2204,50.986177,28.4375,41.921257,29.9375,60.051098,71.0625,22.617967,...,20.000,17.831216,2734,2479,21.433797,311,56,0.0,44.542490,80.184155
14,Rhap-M0006.wav,spont,247,50.816032,38.6375,40.750617,43.7875,60.881447,73.9375,36.639676,...,20.560,12.550607,284,268,13.380282,17,1,0.0,48.913043,83.333333
15,Rhap-D1002.wav,spont,1063,61.379499,29.1125,51.662712,30.7375,71.096286,76.0375,24.506115,...,27.100,20.507996,1303,1202,20.644666,130,29,0.0,44.950100,80.079840
16,Rhap-D1001.wav,planned,2638,52.940718,33.5625,42.112828,36.0625,63.768609,83.1875,30.250190,...,30.000,29.795299,3000,2877,13.800000,175,52,0.0,40.564914,75.786966
17,Rhap-M0004.wav,spont,106,46.440094,33.7450,34.700000,34.0375,58.180189,58.7325,18.396226,...,15.625,13.207547,128,124,18.750000,6,2,0.0,45.238095,88.095238
18,Rhap-D2012.wav,spont,2652,42.774043,32.9875,37.763957,33.8750,47.784129,70.9375,25.565611,...,20.000,15.573152,3159,2963,17.727129,249,53,0.0,39.104868,80.888598
19,Rhap-D2010.wav,spont,2066,65.377281,31.4375,47.628925,32.7125,83.125636,76.0625,23.959342,...,20.000,17.134560,2837,2407,29.044766,483,53,0.0,42.067124,79.138063
20,Rhap-M0019.wav,spont,421,38.085315,22.6125,27.163367,23.4975,49.007262,57.5765,15.558195,...,20.000,12.826603,495,463,16.565657,40,8,0.0,50.730689,85.594990
21,Rhap-M2005.wav,planned,1114,40.797058,32.7250,36.482074,33.9875,45.112042,69.8125,26.211849,...,20.000,14.991023,1215,1172,9.135802,53,10,0.0,33.598659,82.195224
22,Rhap-M1001.wav,spont,733,40.855249,25.7125,31.224594,28.8625,50.485904,64.2125,20.122783,...,27.200,18.826739,988,890,28.643725,126,28,0.0,49.840256,82.428115
23,Rhap-M0007.wav,spont,401,58.678797,44.2375,45.192226,48.1875,72.165368,80.9375,45.760599,...,24.960,15.461347,493,461,20.486815,41,9,0.0,44.025157,78.616352
24,Rhap-M2004.wav,planned,4054,57.032039,34.1875,41.148643,35.1250,72.915434,75.9375,28.034040,...,20.000,20.596941,4305,4252,6.782811,94,41,0.0,36.017296,80.168283
25,Rhap-D2011.wav,planned,2878,43.803065,32.5125,38.122318,33.9375,49.483813,72.5625,24.426685,...,20.000,17.303683,3324,3111,14.380265,245,32,0.0,41.118881,80.994561
26,Rhap-D0003.wav,spont,2015,53.153989,35.7375,44.474855,37.0125,61.833123,78.1875,30.248139,...,20.400,18.461538,2605,2398,25.412668,279,72,0.0,35.738557,76.713972
27,Rhap-D2008.wav,spont,5288,39.384317,26.6875,34.094498,27.8750,44.674136,60.9375,16.121407,...,20.000,13.086233,6143,5774,15.562429,470,101,0.0,48.468574,86.296887
28,Rhap-M0018.wav,spont,589,57.674520,29.6125,36.892390,32.6125,78.456651,78.8025,24.448217,...,23.400,18.845501,697,648,16.929699,59,10,0.0,45.799257,80.297398
29,Rhap-D0006.wav,semi,2485,79.816808,26.8125,61.676222,28.1875,97.957393,80.9500,21.006036,...,20.000,17.384306,3448,2839,29.756381,672,63,0.0,48.067441,80.038174
30,Rhap-M0022.wav,spont,537,57.071415,33.1875,39.965722,36.3375,74.177109,80.1675,27.839851,...,22.300,19.180633,652,591,18.711656,68,7,0.0,33.467418,75.784393
31,Rhap-M0001.wav,spont,340,60.733934,39.1750,43.611426,43.5625,77.856441,88.2225,35.735294,...,20.100,19.117647,402,372,16.169154,33,3,0.0,49.870801,78.811370
32,Rhap-M2001.wav,planned,1630,49.743775,37.5875,37.793620,38.1875,61.693929,66.1875,26.932515,...,20.000,10.981595,1716,1728,6.701632,17,29,0.0,34.843206,83.681765
33,Rhap-D2007.wav,spont,1788,63.213561,30.5000,52.792746,32.1875,73.634376,72.8125,22.986577,...,20.000,16.219239,2533,2177,32.806948,442,86,0.0,42.632696,78.513800
34,Rhap-M0011.wav,spont,367,58.925204,43.6275,48.440266,44.0375,69.410143,84.0145,41.416894,...,20.000,17.438692,432,417,17.129630,24,9,0.0,41.696113,78.916372
35,Rhap-M1003.wav,spont,2067,42.239658,28.1875,32.477577,30.1875,52.001738,66.6875,20.512821,...,23.000,18.577649,2526,2320,19.398258,237,31,0.0,48.122163,83.780437
36,Rhap-M0024.wav,spont,324,46.890478,33.4625,37.707423,35.8750,56.073534,69.4425,26.080247,...,20.140,17.592593,382,357,17.015707,32,7,0.0,34.641407,78.484438
37,Rhap-D2001.wav,semi,4675,42.199612,30.6875,35.400713,32.3125,48.998512,66.3125,21.454545,...,20.000,13.155080,5520,5324,17.844203,336,140,0.0,42.456658,84.489118
38,Rhap-D2013.wav,spont,2116,37.341395,31.7500,34.915418,32.1875,39.767372,62.8125,19.872401,...,20.000,11.672968,2227,2227,6.151774,26,26,0.0,37.494387,86.888190
39,Rhap-M2002.wav,planned,3316,47.517429,33.4875,38.561806,35.1875,56.473052,74.9375,27.457780,...,30.000,23.884198,3811,3616,14.694306,260,65,0.0,42.062744,79.439882
40,Rhap-D0008.wav,spont,1432,56.941264,36.1625,40.343953,39.3125,73.538575,78.1500,32.262570,...,21.200,16.131285,1736,1560,18.951613,201,25,0.0,39.381068,77.973301
41,Rhap-M2003.wav,planned,2149,51.227079,37.8125,38.504543,39.0625,63.949615,70.5625,29.478827,...,20.000,15.588646,2270,2239,6.519824,58,27,0.0,31.581282,79.884675
42,Rhap-M0005.wav,spont,350,60.339186,44.6475,50.447771,46.0875,70.230600,84.5245,43.714286,...,24.450,20.000000,402,379,15.174129,32,9,0.0,40.204866,77.080666
43,Rhap-D0009.wav,spont,2007,56.078691,29.9375,43.600696,33.8125,68.556685,77.9950,24.464375,...,30.000,21.723966,3009,2591,36.955799,528,110,0.0,42.607143,77.357143
44,Rhap-M0021.wav,spont,494,58.032293,34.1625,38.034868,34.7750,78.029717,79.9875,28.846154,...,22.400,20.850202,548,537,12.591241,26,15,0.0,38.525346,78.894009
45,Rhap-D2003.wav,spont,2908,79.072800,34.4875,70.943499,37.6875,87.202101,84.3125,29.522008,...,20.000,16.643741,3943,3461,28.328684,564,82,0.0,41.274986,77.849811
46,Rhap-M0014.wav,spont,224,62.862020,45.1375,51.833996,49.7950,73.890045,97.6120,46.205357,...,20.000,23.214286,249,237,11.646586,16,4,0.0,51.028807,79.835391
47,Rhap-M0015.wav,spont,218,51.266445,38.3375,43.361284,40.3850,59.171606,80.2625,36.238532,...,20.000,17.889908,243,237,12.345679,11,5,0.0,48.333333,82.500000
48,Rhap-D0007.wav,spont,297,62.861726,40.2125,50.240800,41.3275,75.482652,89.9875,37.878788,...,23.600,20.875421,390,339,25.128205,56,5,0.0,42.249657,77.091907
49,Rhap-M0013.wav,spont,369,64.032520,46.6675,48.691795,48.8625,79.373245,89.4025,47.289973,...,29.260,20.867209,449,411,19.599109,46,8,0.0,43.255814,75.116279
50,Rhap-M0012.wav,spont,146,57.882038,44.7625,45.921473,47.8300,69.842603,78.5325,41.780822,...,24.550,13.698630,166,159,12.048193,7,0,0.0,36.923077,81.230769
51,Rhap-M0008.wav,spont,125,58.546760,46.7975,49.706860,49.9875,67.386660,89.1535,46.400000,...,22.300,19.200000,155,139,21.290323,19,3,0.0,38.775510,73.469388
52,Rhap-M0010.wav,spont,149,53.181091,39.6675,40.108171,44.4475,66.254010,81.8525,36.577181,...,20.000,16.107383,191,170,23.036649,23,2,0.0,49.861496,83.656510
53,STYLE_planned,planned,25892,49.511638,34.3125,39.492775,35.6875,59.530500,74.4375,27.537463,...,20.000,19.314846,29234,28018,12.906205,1647,431,0.0,38.580312,80.032139
54,STYLE_semi,semi,11836,52.114490,29.5625,42.525221,31.1875,61.703759,69.4025,21.730314,...,20.000,15.435958,14697,13393,21.535007,1608,304,0.0,43.859025,81.993592
55,STYLE_spont,spont,36828,53.415001,32.1875,43.078999,34.3125,63.751002,75.1125,26.030466,...,20.000,16.829586,46184,41990,22.224147,5102,908,0.0,42.774514,80.440946
56,GLOBAL,ALL,74556,51.852970,32.4375,41.745652,34.3875,61.960289,74.0625,25.871157,...,20.000,17.471431,90115,83401,19.088942,8357,1643,0.0,41.566196,80.557413

In [7]:
dict_to_csv(alignment_store, f'ctc_results/pred_{model_name}_rhap.csv')

# Prepare for MFA

In [8]:
df1=pd.read_csv(f"/vol/experiments3/imbenamor/TAPAS-FRAIS/src/utils/ctc_results/pred_{model_name}_rhap.csv")
df1["filename1"]=[i.split("-")[1].split(".")[0]+"-"+i.split("-")[0]+".wav" for i in df1["filename"]]
df1["speaker_id"]=[i.split("-")[0] for i in df1["filename1"]]
df1 = df1[df1["speaker_id"] != "D2004"]

In [9]:
df1["predicted_phonemes"] = df1["predicted_phonemes"].apply(normalize_phones)
ref_inventory = set()

for seq in df1["predicted_phonemes"].dropna():
    tokens = seq.split()
    ref_inventory.update(tokens)

print(sorted(ref_inventory))
print("Number of unique phonemes:", len(ref_inventory))

['a', 'b', 'd', 'e', 'f', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 's', 't', 'u', 'v', 'w', 'y', 'z', 'ø', 'ŋ', 'œ', 'ɑ̃', 'ɔ', 'ɔ̃', 'ə', 'ɛ', 'ɛ̃', 'ɡ', 'ɲ', 'ʁ', 'ʃ', 'ʒ']
Number of unique phonemes: 34

In [10]:
#Generation des fichiers pour mFA
import os
import torch
import torchaudio
import shutil

corpus_dir = f"/vol/experiments3/imbenamor/TAPAS-FRAIS/mfa_data/mfa_rhap_{model_name}_ctc"
if os.path.exists(corpus_dir):
    shutil.rmtree(corpus_dir)  
os.makedirs(corpus_dir)
target_sr = 16000
wav_path = "/vol/corpora/Rhapsodie/wav16k_corrected_withsilence"
for idx, row in df1.iterrows():
    audio_path = os.path.join(wav_path, row["filename"])
    tmp = os.path.join(wav_path, row["filename1"])
    tokens = row["predicted_phonemes"]
    utt_id = os.path.splitext(os.path.basename(tmp))[0]
    speaker_id = str(row["speaker_id"])  

    # Create speaker folder
    speaker_dir = os.path.join(corpus_dir, speaker_id)
    os.makedirs(speaker_dir, exist_ok=True)
    # Load audio
    waveform, sr = torchaudio.load(audio_path)
    # Resample if needed
    if sr != target_sr:
        resampler = torchaudio.transforms.Resample(orig_freq=sr, new_freq=target_sr)
        waveform = resampler(waveform)

    # Save wav inside speaker folder
    torchaudio.save(
        os.path.join(speaker_dir, f"{utt_id}.wav"),
        waveform,
        target_sr
    )

    # Save lab inside speaker folder
    with open(os.path.join(speaker_dir, f"{utt_id}.lab"), "w", encoding="utf-8") as f:
        f.write(tokens.strip())

/home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/torchaudio/_backend/utils.py:213: UserWarning: In 2.9, this function's implementation will be changed to use torchaudio.load_with_torchcodec` under the hood. Some parameters like ``normalize``, ``format``, ``buffer_size``, and ``backend`` will be ignored. We recommend that you port your code to rely directly on TorchCodec's decoder instead: https://docs.pytorch.org/torchcodec/stable/generated/torchcodec.decoders.AudioDecoder.html#torchcodec.decoders.AudioDecoder.
  warnings.warn(
/home/imbenamor/miniconda3/envs/pyannote_env/lib/python3.10/site-packages/torchaudio/_backend/utils.py:337: UserWarning: In 2.9, this function's implementation will be changed to use torchaudio.save_with_torchcodec` under the hood. Some parameters like format, encoding, bits_per_sample, buffer_size, and ``backend`` will be ignored. We recommend that you port your code to rely directly on TorchCodec's encoder instead: https://docs.pytorch.org/torchcodec/stable/generated/torchcodec.encoders.AudioEncoder
  warnings.warn(

In [11]:
with open(f"/vol/experiments3/imbenamor/TAPAS-FRAIS/mfa_data/output_ph_reco/phoneme_rhap_{model_name}_ctc.txt", "w", encoding="utf-8") as f:
    for ph in ref_inventory:
        f.write(f"{ph} {ph}\n")

# MFA ALIGN: GO to cmd

# MFA alignment

In [12]:
#rhapsodie

import os
import json
from pathlib import Path
import pandas as pd
import pickle
from praatio import textgrid
import os
import json
from pathlib import Path
import pandas as pd
import pickle
style = pd.read_csv("/vol/corpora/Rhapsodie/wav_style.csv")
tg_path = Path(f"/vol/experiments3/imbenamor/TAPAS-FRAIS/mfa_data/align_{model_name}_rhap")
audio_dir = "/vol/corpora/Rhapsodie/wav16k_corrected_withsilence"
textgrid_dir = Path("/vol/corpora/Rhapsodie/TextGrid.phones.sampa")
ref_files = textgrid_dir.glob("*")
full_paths = list(tg_path.rglob("*.TextGrid"))
ref_dict={str(f.stem)[:-4].split("-")[1]+"-"+str(f.stem)[:-4].split("-")[0]:str(f) for f in ref_files}
alignment_store = {}
for hyp_path in full_paths:
    if ".ipynb_checkpoints" not in str(hyp_path):
        stem=hyp_path.stem
        #stem = hyp_path.stem.split("-")[1]+"-"+hyp_path.stem.split("-")[0] #txtgrid from mfa
        if stem not in ref_dict.keys() or stem=="D2004-Rhap":
            continue
    
        ref_path = ref_dict[stem]
        
        #f = hyp_path.stem.split("-")[1]+"-"+hyp_path.stem.split("-")[0] + ".wav"
        f = stem.split("-")[1]+"-"+stem.split("-")[0] + ".wav"
        audio_path = os.path.join(audio_dir, f)
        if os.path.exists(audio_path):
            s = list(style[style["file"] == f.split("-")[1].split(".")[0]]["style"])[0]
            phones_hyp, hyp_intervals = extract_phones_from_textgrid(hyp_path, t="phones")
            ref_alignments = get_reference_alignments(
            ref_path,
            t="sampa"
        )
            pred_alignments=[]
            for i,j,k in hyp_intervals:
                pred_alignments.append({"phoneme":k,"start":i,"end":j})
            
            clean_hyp = clean_alignment_dict(pred_alignments, is_hyp=True)
            clean_ref = clean_alignment_dict(ref_alignments,  is_hyp=False)
            
            
            entry = {
                "file":          f,
                "style":s,
                "ref_intervals": clean_ref,
                "hyp_intervals": clean_hyp,
                "ref_seq":       extract_phoneme_sequence(clean_ref),
                "hyp_seq":       extract_phoneme_sequence(clean_hyp),
            }
            alignment_store[f] = entry

In [13]:
from metrics import *
import pickle
from jiwer import process_words
# (optional) save back so you don't redo it
with open(f"mfa_results/alignment_{model_name}_mfa_rhap.pkl", "wb") as f:
    pickle.dump(alignment_store, f)

In [14]:
from metrics_alignment import *

with open(f"mfa_results/alignment_{model_name}_mfa_rhap.pkl", "rb") as f:
    alignment_store = pickle.load(f)
compute_metrics(alignment_store, f"mfa_results/metrics++_{model_name}_mfa_rhap.csv", per_phoneme_csv=None)

,group,style,K,AAS (ms),Median_start (ms),Mean_start (ms),Median_end (ms),Mean_end (ms),P90 (ms),%>50ms,...,Median_dur (ms),%dur>50ms,N_ref,N_hyp,PER (%),Deletions,Insertions,F1@0ms (%),F1@20ms (%),F1@50ms (%)
0,Rhap-D0003.wav,spont,2015,40.560113,11.9980,39.520237,12.0030,41.599989,67.0518,15.434243,...,21.0010,23.027295,2605,2398,25.412668,279,72,0.239856,65.400760,83.110134
1,Rhap-M0023.wav,spont,549,37.163143,10.4980,37.558179,10.5020,36.768107,53.4427,10.837887,...,13.8940,13.114754,735,652,27.755102,101,18,1.009373,74.116799,87.382841
2,Rhap-D2013.wav,spont,2116,12.029679,7.3015,11.720216,7.3975,12.339142,25.0010,2.079395,...,10.0030,4.631380,2227,2227,6.151774,26,26,1.436911,84.687921,97.215986
3,Rhap-D2010.wav,spont,2066,46.066322,9.7000,45.414342,10.0040,46.718302,60.9979,12.173282,...,19.9790,15.537270,2837,2407,29.044766,483,53,0.038139,73.302822,84.820748
4,Rhap-D0008.wav,spont,1432,39.554594,12.2510,39.553513,12.0065,39.555675,49.9970,9.916201,...,20.0030,14.385475,1736,1560,18.951613,201,25,0.060680,70.509709,88.956311
5,Rhap-D2003.wav,spont,2908,93.034257,10.9965,92.593097,10.9955,93.475416,71.9900,14.047455,...,19.9960,16.540578,3943,3461,28.328684,564,82,0.135062,69.259860,82.549973
6,Rhap-M0022.wav,spont,537,108.641921,13.9000,110.278372,13.9990,107.005469,64.5996,14.152700,...,20.0060,20.297952,652,591,18.711656,68,7,0.000000,66.291231,84.794851
7,Rhap-M0002.wav,spont,413,83.042282,13.2000,83.299569,13.7010,82.784995,97.7700,18.765133,...,21.0010,23.728814,529,471,22.495274,61,3,0.000000,65.000000,81.600000
8,Rhap-D2007.wav,spont,1788,90.808847,11.9960,92.451100,11.8980,89.166593,59.9985,11.633110,...,19.9970,15.212528,2533,2177,32.806948,442,86,0.254777,69.214437,83.906582
9,Rhap-D2011.wav,planned,2878,22.645459,10.0005,21.728561,10.9905,23.562356,44.0045,8.234885,...,19.9960,13.829048,3324,3111,14.380265,245,32,0.062160,74.498834,90.349650
10,Rhap-D0002.wav,semi,2204,42.650705,12.0045,41.300023,12.9895,44.001387,61.7992,14.246824,...,20.0010,19.555354,2734,2479,21.433797,311,56,0.153462,67.370036,84.941492
11,Rhap-D2005.wav,planned,2681,29.390103,9.9950,28.230261,9.9960,30.549944,37.0020,6.191720,...,10.0110,10.630362,3069,2940,14.532421,187,58,1.098352,78.681977,92.161757
12,Rhap-M0021.wav,spont,494,28.991846,11.3500,27.176085,11.9015,30.807607,49.9000,9.919028,...,20.0000,15.587045,548,537,12.591241,26,15,0.184332,70.967742,88.847926
13,Rhap-M0011.wav,spont,367,39.151108,12.2100,39.255905,13.8990,39.046311,48.5830,9.128065,...,15.5000,13.351499,432,417,17.129630,24,9,0.235571,72.555948,90.459364
14,Rhap-D0017.wav,spont,288,57.667212,16.1400,55.178021,16.9005,60.156403,85.0990,18.576389,...,27.0995,28.125000,319,310,11.598746,15,6,0.953895,62.321145,83.942766
15,Rhap-M0005.wav,spont,350,28.256219,12.8515,27.098714,13.6990,29.413723,48.5000,9.285714,...,19.9990,15.428571,402,379,15.174129,32,9,0.256082,70.678617,89.628681
16,Rhap-D0006.wav,semi,2485,82.492630,10.0100,80.826452,10.9960,84.158808,83.0040,14.849095,...,10.0090,13.682093,3448,2839,29.756381,672,63,0.286305,72.530619,83.060283
17,Rhap-D2001.wav,semi,4675,22.240092,8.0090,21.782453,8.3970,22.697732,34.0041,5.604278,...,13.0020,8.877005,5520,5324,17.844203,336,140,0.073774,79.527850,92.180007
18,Rhap-M2003.wav,planned,2149,17.967526,10.9960,16.866813,11.9970,19.068239,40.0003,6.468125,...,20.0020,15.449046,2270,2239,6.519824,58,27,0.443557,73.941007,93.324462
19,Rhap-D0005.wav,spont,1705,58.095044,11.0030,57.495284,11.0010,58.694805,63.0010,13.108504,...,19.9940,15.777126,2412,2029,31.094527,426,43,0.135105,67.957667,82.548975
20,Rhap-M0010.wav,spont,149,37.439326,15.5300,35.393483,15.6400,39.485168,64.5430,16.778523,...,20.0000,16.778523,191,170,23.036649,23,2,1.108033,68.698061,87.534626
21,Rhap-D2006.wav,planned,810,36.971865,12.3495,35.385885,12.6000,38.557846,60.7279,13.703704,...,20.0000,19.135802,943,888,15.164369,65,10,0.000000,67.613326,86.947023
22,Rhap-M1001.wav,spont,733,40.864371,13.8990,39.862269,13.9010,41.866473,70.3980,15.961801,...,20.0000,20.327422,988,890,28.643725,126,28,0.106496,68.796592,84.877529
23,Rhap-D0004.wav,semi,2472,39.167720,12.7500,38.044607,12.9965,40.290833,56.9906,12.762945,...,20.0080,19.660194,2995,2751,18.964942,289,45,0.069614,65.993735,86.355726
24,Rhap-D2002.wav,planned,1863,47.283685,10.2990,47.803513,10.4000,46.763857,51.1000,10.762211,...,19.9970,15.244230,2519,2228,28.066693,342,51,0.674110,71.034337,86.117548
25,Rhap-D0020.wav,spont,251,22.387934,13.3010,22.452167,14.5010,22.323701,43.6000,7.768924,...,15.7990,11.952191,297,275,17.171717,27,5,0.000000,72.727273,89.860140
26,Rhap-M0001.wav,spont,340,31.307544,16.2005,28.791865,17.5055,33.823224,53.0990,10.882353,...,20.0000,18.823529,402,372,16.169154,33,3,0.000000,65.633075,88.372093
27,Rhap-M0024.wav,spont,324,71.485846,11.9040,69.537920,11.6990,73.433772,73.6496,15.432099,...,19.9990,21.913580,382,357,17.015707,32,7,0.811908,66.035183,84.438430
28,Rhap-M0015.wav,spont,218,31.705073,12.9300,29.398890,12.9300,34.011257,47.5000,9.862385,...,19.9990,18.348624,243,237,12.345679,11,5,0.416667,70.000000,90.000000
29,Rhap-M0007.wav,spont,401,23.395567,13.3000,20.928920,13.4600,25.862214,41.3961,7.605985,...,19.1000,13.965087,493,461,20.486815,41,9,1.467505,71.698113,90.146751
30,Rhap-M2005.wav,planned,1114,12.700503,8.6980,12.340838,8.4000,13.060168,26.4990,2.648115,...,10.0010,5.655296,1215,1172,9.135802,53,10,2.597403,82.027650,95.601173
31,Rhap-M0019.wav,spont,421,34.880426,20.2000,35.030689,20.2000,34.730164,55.0690,12.114014,...,23.7000,17.577197,495,463,16.565657,40,8,0.208768,56.993737,85.386221
32,Rhap-M2004.wav,planned,4054,25.852839,10.9730,24.734292,10.9980,26.971385,49.0040,9.866798,...,19.9940,17.291564,4305,4252,6.782811,94,41,0.093491,74.091387,90.849597
33,Rhap-M1003.wav,spont,2067,50.791705,15.0060,49.164399,16.9950,52.419011,76.9930,17.223029,...,26.0120,23.754233,2526,2320,19.398258,237,31,0.123813,65.084606,85.059843
34,Rhap-M2002.wav,planned,3316,33.692727,14.0080,33.355335,14.8995,34.030118,67.0050,15.922799,...,29.9920,27.472859,3811,3616,14.694306,260,65,0.161573,66.163996,85.579642
35,Rhap-M0008.wav,spont,125,41.699140,14.5700,39.963904,15.4300,43.434376,55.8600,12.000000,...,20.0000,18.400000,155,139,21.290323,19,3,1.360544,66.666667,87.074830
36,Rhap-D0007.wav,spont,297,44.151221,14.6000,40.461946,15.1000,47.840495,73.9104,14.309764,...,20.0000,20.875421,390,339,25.128205,56,5,0.274348,66.392318,85.871056
37,Rhap-M0012.wav,spont,146,38.998634,11.8000,38.353973,12.5850,39.643295,51.7040,10.616438,...,20.0000,12.328767,166,159,12.048193,7,0,0.615385,68.923077,90.461538
38,Rhap-M0013.wav,spont,369,64.031973,14.5010,65.319035,14.2010,62.744911,52.6200,10.569106,...,19.8990,15.447154,449,411,19.599109,46,8,0.232558,69.534884,86.511628
39,Rhap-M0003.wav,spont,798,38.878762,12.6000,38.528712,12.2995,39.228812,47.8250,8.834586,...,22.2025,17.418546,937,870,16.008538,78,11,0.553403,68.068622,89.097952
40,Rhap-D0009.wav,spont,2007,61.938952,16.4990,61.734882,15.9970,62.143022,96.7093,22.446437,...,29.9910,25.710015,3009,2591,36.955799,528,110,0.142857,58.964286,78.071429
41,Rhap-M0009.wav,spont,471,35.891896,14.9000,36.076584,14.6980,35.707208,52.2000,10.403397,...,20.0000,14.012739,555,519,16.036036,41,5,0.744879,67.597765,89.199255
42,Rhap-D1001.wav,planned,2638,53.944179,16.5020,50.993685,18.1560,56.894672,95.9870,24.715694,...,30.0220,35.708870,3000,2877,13.800000,175,52,0.136124,59.554194,78.985877
43,Rhap-D1002.wav,spont,1063,55.311357,18.6000,54.782092,18.0030,55.840622,65.0050,16.415804,...,30.0060,24.741298,1303,1202,20.644666,130,29,0.000000,58.043912,82.554890
44,Rhap-D2012.wav,spont,2652,19.734655,9.9930,19.563546,9.8025,19.905765,39.0017,7.296380,...,10.0230,10.633484,3159,2963,17.727129,249,53,1.535446,76.804966,91.081346
45,Rhap-M0014.wav,spont,224,27.591386,12.7505,25.750531,13.4300,29.432241,46.3103,8.258929,...,19.9990,14.285714,249,237,11.646586,16,4,1.646091,69.135802,91.358025
46,Rhap-M0016.wav,spont,514,83.373617,19.6260,81.769879,20.0000,84.977354,168.5704,23.735409,...,30.0000,32.101167,633,585,21.011058,62,14,0.328407,56.157635,78.981938
47,Rhap-M2001.wav,planned,1630,15.895565,9.8995,14.999267,10.0040,16.791863,34.7400,4.355828,...,19.9970,11.901840,1716,1728,6.701632,17,29,0.406504,77.177700,95.934959
48,Rhap-M0018.wav,spont,589,43.538832,11.0000,43.539452,11.4030,43.538212,60.6009,11.629881,...,19.9990,16.638370,697,648,16.929699,59,10,0.743494,70.780669,88.178439
49,Rhap-D2009.wav,planned,2759,19.984533,9.0040,19.419738,9.0060,20.549328,37.1593,6.922798,...,19.9970,12.903226,3062,2967,11.724363,151,56,0.033173,77.492121,91.789683
50,Rhap-M0006.wav,spont,247,22.946893,13.0000,22.890170,13.0990,23.003615,39.2000,6.072874,...,18.1600,9.716599,284,268,13.380282,17,1,0.362319,75.000000,92.028986
51,Rhap-M0004.wav,spont,106,27.220755,11.1000,25.370283,11.7400,29.071226,57.9970,12.264151,...,17.1100,16.981132,128,124,18.750000,6,2,0.000000,79.365079,91.269841
52,Rhap-D2008.wav,spont,5288,21.731061,9.0090,21.810072,9.0130,21.652051,37.9885,6.703858,...,11.0090,10.117247,6143,5774,15.562429,470,101,0.117479,78.643954,91.063187
53,STYLE_planned,planned,25892,29.146073,10.9910,28.169451,11.0010,30.122694,51.9990,10.524486,...,20.0000,17.847211,29234,28018,12.906205,1647,431,0.398239,72.500524,89.310417
54,STYLE_semi,semi,11836,42.226375,10.0050,41.209718,10.3990,43.243032,52.9960,10.649713,...,19.9655,14.126394,14697,13393,21.535007,1608,304,0.135279,72.936988,87.604130
55,STYLE_spont,spont,36828,46.140908,11.8000,45.730155,11.9905,46.551662,56.9025,11.727490,...,19.9980,16.153470,46184,41990,22.224147,5102,908,0.383333,70.310976,86.522104
56,GLOBAL,ALL,74556,39.617453,11.0010,38.913995,11.0080,40.320912,54.1000,11.138607,...,19.9980,16.419872,90115,83401,19.088942,8357,1643,0.348095,71.458540,87.617280